server {
    listen 80;
    server_name talkymate.com www.talkymate.com;

    root /var/www/talkymate;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
